"""English textbook data from elementary basics to high-school reading."""

textbook_levels = [
    {"id": "elementary", "number": "01", "title": "小学英語", "english_title": "ELEMENTARY", "description": "単語と短い文から、英語の順番に慣れます。"},
    {"id": "junior-high", "number": "02", "title": "中学英語", "english_title": "JUNIOR HIGH", "description": "時制・疑問・比較など、英文の基本ルールを身につけます。"},
    {"id": "high-school", "number": "03", "title": "高校英語", "english_title": "HIGH SCHOOL", "description": "長い英文を文型・節・修飾に分けて読みます。"},
]


def make_textbook_lesson(lesson_id, level, number, title, grammar, example,
                         translation, chunks, words, image):
    """Build one readable lesson dictionary from simple lists and strings."""
    return {
        "id": lesson_id,
        "level": level,
        "number": number,
        "title": title,
        "grammar": grammar,
        "example": example,
        "translation": translation,
        "chunks": [
            {"text": text, "meaning": meaning, "job": job}
            for text, meaning, job in chunks
        ],
        "words": [
            {"word": word, "meaning": meaning}
            for word, meaning in words
        ],
        "image": image,
    }


textbook_lessons = [
    # 小学英語：単語と1文の基本
    make_textbook_lesson(
        "i-you",
        "elementary",
        1,
        "I と YOU",
        "I は自分、you は相手を指します。英語は最初に『誰の話か』を置きます。",
        "I am Ken.",
        "私はケンです。",
        [
            ("I", "私は", "主語"),
            ("am", "〜です", "Iと説明をつなぐ"),
            ("Ken", "ケン", "名前"),
        ],
        [
            ("I", "私"),
            ("you", "あなた"),
            ("my", "私の"),
            ("your", "あなたの"),
            ("name", "名前"),
            ("hello", "こんにちは"),
        ],
        "自分を指し、それから名前を伝える。",
    ),
    make_textbook_lesson(
        "am-is-are",
        "elementary",
        2,
        "AM / IS / ARE",
        "am・is・are は、人や物と、その名前・状態・場所をつなぐbe動詞です。Iにはam、1人・1つにはis、複数やyouにはareを使います。",
        "The room is quiet.",
        "その部屋は静かです。",
        [
            ("The room", "その部屋は", "人・物"),
            ("is", "〜です", "前後をつなぐ"),
            ("quiet", "静かな", "状態"),
        ],
        [
            ("am", "〜です（I）"),
            ("is", "〜です（1人・1つ）"),
            ("are", "〜です（you・複数）"),
            ("room", "部屋"),
            ("quiet", "静かな"),
            ("ready", "準備ができた"),
        ],
        "部屋と『静か』という状態を is で結ぶ。",
    ),
    make_textbook_lesson(
        "a-an-the",
        "elementary",
        3,
        "A / AN / THE",
        "a・an は『ある1つ』、the は話す人も聞く人も分かる『その』です。どれも名詞の前に置きます。",
        "The book is on a desk.",
        "その本は机の上にあります。",
        [
            ("The", "その", "特定する"),
            ("book", "本は", "物"),
            ("is", "あります", "場所につなぐ"),
            ("on", "〜の上に", "位置"),
            ("a desk", "ある机", "場所"),
        ],
        [
            ("a", "1つの"),
            ("an", "1つの（母音の前）"),
            ("the", "その"),
            ("book", "本"),
            ("desk", "机"),
            ("apple", "りんご"),
        ],
        "特定の本が、どれか1つの机の上にある。",
    ),
    make_textbook_lesson(
        "this-that",
        "elementary",
        4,
        "THIS / THAT",
        "this は近くの『これ』、that は離れた『あれ』です。複数なら these / those になります。",
        "This is my computer.",
        "これは私のコンピューターです。",
        [
            ("This", "これは", "近くの物"),
            ("is", "〜です", "前後をつなぐ"),
            ("my computer", "私のコンピューター", "説明"),
        ],
        [
            ("this", "これ"),
            ("that", "あれ"),
            ("these", "これら"),
            ("those", "あれら"),
            ("computer", "コンピューター"),
            ("phone", "電話"),
        ],
        "近くのコンピューターを指さす。",
    ),
    make_textbook_lesson(
        "numbers-time",
        "elementary",
        5,
        "数字と時刻",
        "時刻は at + 時刻、曜日は on + 曜日で表します。数字を見たら何の数字かも確認します。",
        "The class starts at nine.",
        "授業は9時に始まります。",
        [
            ("The class", "その授業は", "主語"),
            ("starts", "始まります", "動作"),
            ("at nine", "9時に", "時刻"),
        ],
        [
            ("one", "1"),
            ("five", "5"),
            ("nine", "9"),
            ("time", "時間"),
            ("Monday", "月曜日"),
            ("start", "始まる"),
        ],
        "時計が9時になり授業が始まる。",
    ),
    make_textbook_lesson(
        "people-family",
        "elementary",
        6,
        "人と家族",
        "he は男性1人、she は女性1人、they は複数の人や物を指します。名前の代わりに使える語です。",
        "She is my sister.",
        "彼女は私の姉／妹です。",
        [
            ("She", "彼女は", "主語"),
            ("is", "〜です", "前後をつなぐ"),
            ("my sister", "私の姉／妹", "説明"),
        ],
        [
            ("he", "彼"),
            ("she", "彼女"),
            ("they", "彼ら／それら"),
            ("family", "家族"),
            ("brother", "兄／弟"),
            ("sister", "姉／妹"),
        ],
        "女性1人を指し、自分との関係を伝える。",
    ),
    make_textbook_lesson(
        "in-on-at",
        "elementary",
        7,
        "IN / ON / AT",
        "in は中、on は面の上、at は一点を示します。日本語訳より位置の絵で覚えます。",
        "The keys are in the box.",
        "鍵は箱の中にあります。",
        [
            ("The keys", "その鍵は", "主語"),
            ("are", "あります", "場所につなぐ"),
            ("in", "〜の中に", "位置"),
            ("the box", "その箱", "場所"),
        ],
        [
            ("in", "〜の中に"),
            ("on", "〜の上に"),
            ("at", "〜で／〜に"),
            ("key", "鍵"),
            ("box", "箱"),
            ("place", "場所"),
        ],
        "箱の内側に鍵が入っている。",
    ),
    make_textbook_lesson(
        "basic-verbs",
        "elementary",
        8,
        "基本の動作",
        "be動詞以外の動作を表す語を一般動詞と呼びます。主語のあとに『何をする』を置きます。",
        "We read the report.",
        "私たちは報告書を読みます。",
        [
            ("We", "私たちは", "主語"),
            ("read", "読みます", "動作"),
            ("the report", "その報告書を", "対象"),
        ],
        [
            ("go", "行く"),
            ("come", "来る"),
            ("read", "読む"),
            ("write", "書く"),
            ("eat", "食べる"),
            ("work", "働く"),
        ],
        "チームで報告書を読む。",
    ),
    make_textbook_lesson(
        "like-want-have",
        "elementary",
        9,
        "LIKE / WANT / HAVE",
        "like は好き、want は欲しい、have は持っている。後ろに好きな物・欲しい物・持つ物を置きます。",
        "I have a new camera.",
        "私は新しいカメラを持っています。",
        [
            ("I", "私は", "主語"),
            ("have", "持っています", "動作"),
            ("a new camera", "新しいカメラを", "対象"),
        ],
        [
            ("like", "好き"),
            ("want", "欲しい"),
            ("have", "持っている"),
            ("new", "新しい"),
            ("camera", "カメラ"),
            ("game", "ゲーム"),
        ],
        "自分の手元に新しいカメラがある。",
    ),
    make_textbook_lesson(
        "can-cannot",
        "elementary",
        10,
        "CAN / CANNOT",
        "can + 動詞で『〜できる』、cannot + 動詞で『〜できない』です。can の後ろは動詞の元の形です。",
        "You can open the file.",
        "あなたはそのファイルを開けます。",
        [
            ("You", "あなたは", "主語"),
            ("can", "〜できます", "可能"),
            ("open", "開く", "動作"),
            ("the file", "そのファイルを", "対象"),
        ],
        [
            ("can", "できる"),
            ("cannot", "できない"),
            ("open", "開く"),
            ("close", "閉じる"),
            ("use", "使う"),
            ("file", "ファイル"),
        ],
        "ファイルのアイコンを押して開く。",
    ),
    make_textbook_lesson(
        "and-but-or",
        "elementary",
        11,
        "AND / BUT / OR",
        "and は追加、but は反対、or は選択です。単語と単語、文と文をつなぐ接続詞です。",
        "The task is simple but important.",
        "その作業は簡単ですが重要です。",
        [
            ("The task", "その作業は", "主語"),
            ("is simple", "簡単です", "状態1"),
            ("but", "しかし", "反対につなぐ"),
            ("important", "重要です", "状態2"),
        ],
        [
            ("and", "そして／〜と"),
            ("but", "しかし"),
            ("or", "または"),
            ("simple", "簡単な"),
            ("important", "重要な"),
            ("task", "作業"),
        ],
        "簡単という札と重要という札を but でつなぐ。",
    ),
    make_textbook_lesson(
        "question-words",
        "elementary",
        12,
        "疑問詞",
        "what は何、who は誰、where はどこ、when はいつ、how はどうやって。知りたい情報を文の先頭に置きます。",
        "Where is the station?",
        "駅はどこですか。",
        [
            ("Where", "どこ", "知りたい情報"),
            ("is", "〜ですか", "疑問の形"),
            ("the station", "その駅は", "探す場所"),
        ],
        [
            ("what", "何"),
            ("who", "誰"),
            ("where", "どこ"),
            ("when", "いつ"),
            ("why", "なぜ"),
            ("how", "どのように"),
        ],
        "地図を見ながら駅の場所を尋ねる。",
    ),

    # 中学英語：英文を作る基本ルール
    make_textbook_lesson(
        "svo",
        "junior-high",
        1,
        "主語・動詞・目的語",
        "英語の中心は『誰が + する + 何を』です。この3つを先に探すと長い文も読みやすくなります。",
        "The engineer checks the machine.",
        "技術者はその機械を確認します。",
        [
            ("The engineer", "技術者は", "主語 S"),
            ("checks", "確認します", "動詞 V"),
            ("the machine", "その機械を", "目的語 O"),
        ],
        [
            ("subject", "主語"),
            ("verb", "動詞"),
            ("object", "目的語"),
            ("engineer", "技術者"),
            ("check", "確認する"),
            ("machine", "機械"),
        ],
        "技術者から確認動作、機械へ矢印をつなぐ。",
    ),
    make_textbook_lesson(
        "third-person-s",
        "junior-high",
        2,
        "動詞のS",
        "現在の習慣で主語が he / she / it / 1人 / 1つなら、動詞に s を付けます。",
        "She updates the schedule every day.",
        "彼女は毎日予定を更新します。",
        [
            ("She", "彼女は", "3人称単数"),
            ("updates", "更新します", "s付きの動詞"),
            ("the schedule", "予定を", "対象"),
            ("every day", "毎日", "頻度"),
        ],
        [
            ("update", "更新する"),
            ("schedule", "予定"),
            ("every", "毎〜"),
            ("day", "日"),
            ("usually", "普段"),
            ("often", "よく"),
        ],
        "毎日、予定表の内容を書き換える。",
    ),
    make_textbook_lesson(
        "do-does",
        "junior-high",
        3,
        "DO / DOES と否定・疑問",
        "一般動詞の疑問文は Do / Does を先頭へ、否定文は do not / does not を動詞の前へ置きます。",
        "Does this program support Python?",
        "このプログラムはPythonに対応していますか。",
        [
            ("Does", "〜しますか", "疑問を作る"),
            ("this program", "このプログラムは", "主語"),
            ("support", "対応する", "動作"),
            ("Python", "Pythonに", "対象"),
        ],
        [
            ("do", "する／疑問を作る"),
            ("does", "する（3人称）"),
            ("not", "〜ない"),
            ("program", "プログラム"),
            ("support", "対応する"),
            ("language", "言語"),
        ],
        "対応表を見ながらPythonが使えるか尋ねる。",
    ),
    make_textbook_lesson(
        "past-tense",
        "junior-high",
        4,
        "過去形",
        "すでに終わったことは過去形にします。規則動詞は -ed、不規則動詞は went / saw / made など形が変わります。",
        "We completed the test yesterday.",
        "私たちは昨日テストを完了しました。",
        [
            ("We", "私たちは", "主語"),
            ("completed", "完了しました", "過去の動作"),
            ("the test", "そのテストを", "対象"),
            ("yesterday", "昨日", "過去の時"),
        ],
        [
            ("complete", "完了する"),
            ("yesterday", "昨日"),
            ("last", "前の"),
            ("went", "行った"),
            ("made", "作った"),
            ("finished", "終えた"),
        ],
        "昨日の欄にテスト完了の印がある。",
    ),
    make_textbook_lesson(
        "future",
        "junior-high",
        5,
        "未来 WILL / BE GOING TO",
        "will はその場の判断や予測、be going to は決めた予定に使います。どちらも後ろは動詞の元の形です。",
        "The meeting will begin at ten.",
        "会議は10時に始まります。",
        [
            ("The meeting", "会議は", "主語"),
            ("will", "〜する予定です", "未来"),
            ("begin", "始まる", "動作"),
            ("at ten", "10時に", "時刻"),
        ],
        [
            ("will", "〜するだろう"),
            ("future", "未来"),
            ("begin", "始まる"),
            ("plan", "予定"),
            ("tomorrow", "明日"),
            ("next", "次の"),
        ],
        "未来の10時に会議開始の印を置く。",
    ),
    make_textbook_lesson(
        "progressive",
        "junior-high",
        6,
        "進行形",
        "be動詞 + 動詞ing で『今〜している』という途中の動作を表します。",
        "The team is testing the new system.",
        "チームは新しいシステムをテストしています。",
        [
            ("The team", "チームは", "主語"),
            ("is", "〜しています", "進行形のbe動詞"),
            ("testing", "テストしている", "途中の動作"),
            ("the new system", "新しいシステムを", "対象"),
        ],
        [
            ("testing", "テストしている"),
            ("working", "働いている"),
            ("running", "動いている"),
            ("now", "今"),
            ("team", "チーム"),
            ("system", "システム"),
        ],
        "今まさにシステムのテストが進んでいる。",
    ),
    make_textbook_lesson(
        "must-should",
        "junior-high",
        7,
        "MUST / SHOULD",
        "must は強い義務、should は提案や『〜した方がよい』です。後ろには動詞の元の形を置きます。",
        "Users must enter a password.",
        "利用者はパスワードを入力しなければなりません。",
        [
            ("Users", "利用者は", "主語"),
            ("must", "〜しなければならない", "義務"),
            ("enter", "入力する", "動作"),
            ("a password", "パスワードを", "対象"),
        ],
        [
            ("must", "必ず〜する"),
            ("should", "〜すべき"),
            ("may", "〜かもしれない"),
            ("enter", "入力する"),
            ("password", "パスワード"),
            ("rule", "規則"),
        ],
        "ログイン画面でパスワード入力が必須になっている。",
    ),
    make_textbook_lesson(
        "to-ing",
        "junior-high",
        8,
        "TO DO / DOING",
        "to + 動詞は目的やこれからすること、動詞ingは行動そのものを名詞のように扱います。",
        "I use Python to create tools.",
        "私はツールを作るためにPythonを使います。",
        [
            ("I", "私は", "主語"),
            ("use", "使います", "動作"),
            ("Python", "Pythonを", "対象"),
            ("to create tools", "ツールを作るために", "目的"),
        ],
        [
            ("create", "作る"),
            ("learn", "学ぶ"),
            ("use", "使う"),
            ("tool", "道具"),
            ("purpose", "目的"),
            ("practice", "練習する"),
        ],
        "Pythonから自作ツールへ目的の矢印を伸ばす。",
    ),
    make_textbook_lesson(
        "comparison",
        "junior-high",
        9,
        "比較",
        "-er / more で『より〜』、the -est / the most で『最も〜』を表します。than の後ろに比較相手が来ます。",
        "This method is faster than the old one.",
        "この方法は古い方法より速いです。",
        [
            ("This method", "この方法は", "主語"),
            ("is faster", "より速いです", "比較"),
            ("than", "〜より", "比較相手につなぐ"),
            ("the old one", "古い方法", "比較相手"),
        ],
        [
            ("fast", "速い"),
            ("faster", "より速い"),
            ("best", "最も良い"),
            ("than", "〜より"),
            ("method", "方法"),
            ("old", "古い"),
        ],
        "新しい方法の速度バーが古い方法より長い。",
    ),
    make_textbook_lesson(
        "passive",
        "junior-high",
        10,
        "受け身",
        "be動詞 + 過去分詞で『〜される』を表します。誰がしたかより、対象や結果を中心に伝えます。",
        "The data is stored in a file.",
        "データはファイルに保存されます。",
        [
            ("The data", "データは", "される対象"),
            ("is", "〜されます", "受け身のbe動詞"),
            ("stored", "保存される", "過去分詞"),
            ("in a file", "ファイルに", "保存場所"),
        ],
        [
            ("data", "データ"),
            ("store", "保存する"),
            ("stored", "保存された"),
            ("file", "ファイル"),
            ("send", "送る"),
            ("use", "使う"),
        ],
        "データがファイルの中へ保存される。",
    ),
    make_textbook_lesson(
        "present-perfect",
        "junior-high",
        11,
        "現在完了",
        "have / has + 過去分詞で、過去から今への経験・継続・完了を表します。",
        "We have finished the update.",
        "私たちは更新を終えました。",
        [
            ("We", "私たちは", "主語"),
            ("have", "〜した", "現在完了"),
            ("finished", "終えた", "過去分詞"),
            ("the update", "その更新を", "対象"),
        ],
        [
            ("have", "〜したことがある／〜した"),
            ("finish", "終える"),
            ("already", "すでに"),
            ("yet", "まだ／もう"),
            ("since", "〜以来"),
            ("for", "〜の間"),
        ],
        "更新作業が完了し、今は完了状態になっている。",
    ),
    make_textbook_lesson(
        "relative-who-which",
        "junior-high",
        12,
        "WHO / WHICH / THAT",
        "who は人、which は物、that は人・物を後ろから詳しく説明する関係詞です。",
        "The tool that checks files is useful.",
        "ファイルを確認するそのツールは便利です。",
        [
            ("The tool", "そのツールは", "説明される名詞"),
            ("that", "その〜は", "説明をつなぐ"),
            ("checks files", "ファイルを確認する", "ツールの説明"),
            ("is useful", "便利です", "文の中心"),
        ],
        [
            ("who", "〜する人"),
            ("which", "〜する物"),
            ("that", "〜する人／物"),
            ("useful", "便利な"),
            ("tool", "ツール"),
            ("file", "ファイル"),
        ],
        "ファイルを確認する機能を持つツールを思い浮かべる。",
    ),

    # 高校英語：長い文の読み方
    make_textbook_lesson(
        "five-patterns",
        "high-school",
        1,
        "5文型の骨格",
        "長い英文でも中心は S・V・O・C の組み合わせです。まず主語と動詞、その後ろが対象か説明かを見ます。",
        "The update made the system stable.",
        "その更新によってシステムは安定しました。",
        [
            ("The update", "その更新が", "S 主語"),
            ("made", "〜にしました", "V 動詞"),
            ("the system", "システムを", "O 目的語"),
            ("stable", "安定した状態に", "C 説明"),
        ],
        [
            ("pattern", "型"),
            ("subject", "主語"),
            ("object", "目的語"),
            ("complement", "補語"),
            ("stable", "安定した"),
            ("make", "〜にする"),
        ],
        "更新がシステムを安定状態へ変える。",
    ),
    make_textbook_lesson(
        "that-clause",
        "high-school",
        2,
        "THAT節",
        "that + 文を一つの『内容』として扱います。think / know / show / indicate の後ろでよく使います。",
        "The report shows that sales increased.",
        "報告書は売上が増加したことを示しています。",
        [
            ("The report", "報告書は", "主語"),
            ("shows", "示します", "動詞"),
            ("that", "〜ということを", "内容につなぐ"),
            ("sales increased", "売上が増加した", "内容"),
        ],
        [
            ("show", "示す"),
            ("indicate", "示す"),
            ("report", "報告書"),
            ("sales", "売上"),
            ("increase", "増える"),
            ("result", "結果"),
        ],
        "報告書の中に売上上昇グラフがある。",
    ),
    make_textbook_lesson(
        "participles",
        "high-school",
        3,
        "分詞の説明",
        "動詞ing は『〜している』、過去分詞は『〜された』として名詞を前後から説明します。",
        "The file attached to the email contains the details.",
        "メールに添付されたファイルに詳細が含まれています。",
        [
            ("The file", "そのファイルには", "主語"),
            ("attached to the email", "メールに添付された", "主語の説明"),
            ("contains", "含まれています", "動詞"),
            ("the details", "詳細が", "対象"),
        ],
        [
            ("attached", "添付された"),
            ("containing", "含んでいる"),
            ("detail", "詳細"),
            ("email", "メール"),
            ("document", "書類"),
            ("include", "含む"),
        ],
        "メールの添付ファイルを開くと詳細が入っている。",
    ),
    make_textbook_lesson(
        "relative-clauses",
        "high-school",
        4,
        "関係詞の長い説明",
        "関係詞から次の動詞までを括弧に入れ、先に文の中心を見つけます。",
        "Employees who complete the course receive a certificate.",
        "コースを修了した従業員は証明書を受け取ります。",
        [
            ("Employees", "従業員は", "主語の中心"),
            ("who complete the course", "コースを修了した", "主語の説明"),
            ("receive", "受け取ります", "文の動詞"),
            ("a certificate", "証明書を", "対象"),
        ],
        [
            ("employee", "従業員"),
            ("complete", "修了する"),
            ("course", "講座"),
            ("receive", "受け取る"),
            ("certificate", "証明書"),
            ("qualify", "資格を得る"),
        ],
        "修了マークのある従業員へ証明書を渡す。",
    ),
    make_textbook_lesson(
        "perfect-tenses",
        "high-school",
        5,
        "完了形と時間軸",
        "have done は今まで、had done は過去のある時点より前、will have done は未来の時点までの完了です。",
        "The team had solved the issue before noon.",
        "チームは正午前にその問題を解決していました。",
        [
            ("The team", "チームは", "主語"),
            ("had solved", "解決していました", "過去より前の完了"),
            ("the issue", "その問題を", "対象"),
            ("before noon", "正午前に", "基準時"),
        ],
        [
            ("solve", "解決する"),
            ("issue", "問題"),
            ("before", "〜より前"),
            ("after", "〜の後"),
            ("already", "すでに"),
            ("deadline", "期限"),
        ],
        "正午の線より左側に解決済みの印がある。",
    ),
    make_textbook_lesson(
        "modal-nuance",
        "high-school",
        6,
        "助動詞のニュアンス",
        "must は強い義務、may は可能性・許可、should は提案、could は控えめな可能・依頼です。",
        "The delay may affect the schedule.",
        "その遅れは予定に影響する可能性があります。",
        [
            ("The delay", "その遅れは", "主語"),
            ("may", "〜かもしれません", "可能性"),
            ("affect", "影響する", "動詞"),
            ("the schedule", "予定に", "対象"),
        ],
        [
            ("may", "〜かもしれない"),
            ("might", "〜かもしれない"),
            ("could", "〜の可能性がある"),
            ("affect", "影響する"),
            ("delay", "遅れ"),
            ("schedule", "予定"),
        ],
        "遅れから予定表へ影響の矢印が伸びる。",
    ),
    make_textbook_lesson(
        "conditionals",
        "high-school",
        7,
        "条件 IF / UNLESS",
        "if は『もし〜なら』、unless は『もし〜でなければ』です。条件のまとまりと結果のまとまりを分けます。",
        "If the test succeeds, the program will continue.",
        "テストが成功すれば、プログラムは続行します。",
        [
            ("If", "もし〜なら", "条件を開始"),
            ("the test succeeds", "テストが成功する", "条件"),
            ("the program", "プログラムは", "結果の主語"),
            ("will continue", "続行します", "結果"),
        ],
        [
            ("if", "もし〜なら"),
            ("unless", "〜でない限り"),
            ("condition", "条件"),
            ("succeed", "成功する"),
            ("fail", "失敗する"),
            ("continue", "続ける"),
        ],
        "成功の分岐から続行ルートへ進む。",
    ),
    make_textbook_lesson(
        "complex-passive",
        "high-school",
        8,
        "受け身の定型表現",
        "be expected to / be required to / be allowed to は、告知や規則で頻出する受け身表現です。",
        "Applicants are required to submit two documents.",
        "応募者は書類を2点提出する必要があります。",
        [
            ("Applicants", "応募者は", "主語"),
            ("are required to", "〜する必要があります", "義務の受け身"),
            ("submit", "提出する", "動作"),
            ("two documents", "書類を2点", "対象"),
        ],
        [
            ("applicant", "応募者"),
            ("required", "必要とされる"),
            ("expected", "期待される"),
            ("allowed", "許可される"),
            ("submit", "提出する"),
            ("document", "書類"),
        ],
        "応募者の提出欄に書類2点が必要と表示される。",
    ),
    make_textbook_lesson(
        "verb-patterns",
        "high-school",
        9,
        "動詞の後ろの形",
        "want to do、enjoy doing、ask 人 to do のように、動詞ごとに後ろへ続く形が決まります。",
        "The manager asked us to revise the plan.",
        "管理者は私たちに計画を修正するよう求めました。",
        [
            ("The manager", "管理者は", "主語"),
            ("asked us", "私たちに求めました", "動作と相手"),
            ("to revise", "修正するよう", "求めた動作"),
            ("the plan", "計画を", "対象"),
        ],
        [
            ("ask", "頼む"),
            ("want", "望む"),
            ("enjoy", "楽しむ"),
            ("revise", "修正する"),
            ("plan", "計画"),
            ("decide", "決める"),
        ],
        "管理者から私たちへ計画修正の依頼が届く。",
    ),
    make_textbook_lesson(
        "connectors",
        "high-school",
        10,
        "論理をつなぐ語",
        "however は逆、therefore は結果、in addition は追加、for example は具体例を示します。",
        "The software is expensive; however, it saves time.",
        "そのソフトは高価ですが、時間を節約できます。",
        [
            ("The software is expensive", "そのソフトは高価です", "事実1"),
            ("however", "しかし", "逆につなぐ"),
            ("it saves", "それは節約します", "事実2の動作"),
            ("time", "時間を", "対象"),
        ],
        [
            ("however", "しかし"),
            ("therefore", "したがって"),
            ("addition", "追加"),
            ("example", "例"),
            ("expensive", "高価な"),
            ("save", "節約する"),
        ],
        "高い価格と時間節約の利点を however で対比する。",
    ),
    make_textbook_lesson(
        "long-sentence",
        "high-school",
        11,
        "長文を切って読む",
        "カンマ・前置詞・関係詞・接続詞で区切り、最初に文の主語と動詞だけを取ります。",
        "The system, which was updated last week, is now more reliable.",
        "先週更新されたそのシステムは、現在より信頼性が高くなっています。",
        [
            ("The system", "そのシステムは", "主語の中心"),
            ("which was updated last week", "先週更新された", "追加説明"),
            ("is", "〜です", "文の動詞"),
            ("now more reliable", "現在より信頼性が高い", "状態"),
        ],
        [
            ("reliable", "信頼できる"),
            ("system", "システム"),
            ("update", "更新する"),
            ("now", "現在"),
            ("more", "より"),
            ("recent", "最近の"),
        ],
        "先週の更新から、現在の安定したシステムへ時間軸を描く。",
    ),
    make_textbook_lesson(
        "toeic-tech-reading",
        "high-school",
        12,
        "TOEIC・技術英文",
        "業務英文は『誰が・何をする・対象・条件』、技術文書は『機能・動作・入力・結果』を探します。",
        "The application returns an error if the file is missing.",
        "ファイルが見つからない場合、アプリケーションはエラーを返します。",
        [
            ("The application", "アプリケーションは", "主語／機能"),
            ("returns", "返します", "動作"),
            ("an error", "エラーを", "結果"),
            ("if the file is missing", "ファイルがない場合", "条件"),
        ],
        [
            ("application", "アプリケーション"),
            ("return", "返す"),
            ("error", "エラー"),
            ("missing", "見つからない"),
            ("input", "入力"),
            ("output", "出力"),
        ],
        "ファイルなしの条件からエラー結果へ分岐する。",
    ),
]
